#Playground: https://rhysd.github.io/actionlint/
name: Garcia CI

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test:cov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  Build:
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Build Docker Image
      run: docker build -t img .
      env:
        DOCKER_BUILDKIT: 1

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Push Docker Image
      run: |
        IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/cep-api
        # Regex pra deixar tudo minusculo
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        IMAGE_TAG=${{ steps.extract_branch.outputs.branch }}
        docker tag img $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
        echo imagem gerada: $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
